version: '3'
services:
  prod:
    image: magm19/microblog:latest
    container_name: microblog
    environment:
      - SECRET_KEY=MY_SECRET_KEY
      - DATABASE_URL=mysql+pymysql://microblog:pass@dbserver/microblog
    ports:
      - '8000:5000'
    restart: 
      'always'
    
  mysql:
    image: mysql/mysql-server:5.7
    container_name: mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=microblog
      - MYSQL_USER=microblog
      - MYSQL_PASSWORD=pass
    restart:
      'always'
  
  test:
    container_name: test
    build:
      context: ./docker/Dockerfile_test
    image: test:latest
    volumes:
      - .:/home/microblog/volume