FROM python:3.8

WORKDIR /home/microblog

COPY requirements requirements
COPY test.sh .

RUN python -m venv .venv 
RUN .venv/bin/pip3 install -r requirements/test.txt 
RUN .venv/bin/pip3 install py pytest coverage pylint 
RUN chmod +x test.sh

ENTRYPOINT ["./test.sh" ]