FROM python:3.8-alpine

WORKDIR /home/microblog

COPY requirements requirements
COPY requirements.txt microblog.py test.sh ./

RUN python -m venv .venv
RUN apk add build-base=0.5-r2 --no-cache && \
    .venv/bin/pip3 install -r requirements/test.txt && \
    chmod +x test.sh

ENTRYPOINT ["./test.sh"]